services:
  gatus:
    image: twinproduction/gatus:v5
    restart: unless-stopped
    environment:
      SERVICE_FQDN_GATUS_8080: /
      GATUS_CONFIG_PATH: /config/config.yaml
      GATUS_LOG_LEVEL: WARN
    volumes:
      - ./config/gatus.yaml:/config/config.yaml:ro
      - gatus-data:/data
    expose:
      - "8080"

volumes:
  gatus-data:
